import { Observation } from "../observations";
import { Deduction } from "./Deduction";
import { RuleCatalog } from "../rules";

export class DeductionEngine {

    static analyze(observations: Observation[]): Deduction[] {

        const deductions: Deduction[] = [];

        const observationIds = observations.map(o => o.id);

        RuleCatalog.forEach(rule => {

            const match = rule.observations.every(id =>
                observationIds.includes(id)
            );

            if (match) {

                deductions.push({

                    id: rule.deduction,

                    title: rule.deduction,

                    description: "Deduction generated by Rule Engine.",

                    confidence: rule.confidence

                });

            }

        });

        return deductions;

    }

}